/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables.records;

import edu.java.domain.jooq.tables.ChatUrl;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ChatUrlRecord extends UpdatableRecordImpl<ChatUrlRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CHAT_URL.URL_ID</code>.
     */
    public void setUrlId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>CHAT_URL.URL_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getUrlId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>CHAT_URL.CHAT_ID</code>.
     */
    public void setChatId(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>CHAT_URL.CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return ChatUrl.CHAT_URL.URL_ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return ChatUrl.CHAT_URL.CHAT_ID;
    }

    @Override
    @NotNull
    public Long component1() {
        return getUrlId();
    }

    @Override
    @NotNull
    public Long component2() {
        return getChatId();
    }

    @Override
    @NotNull
    public Long value1() {
        return getUrlId();
    }

    @Override
    @NotNull
    public Long value2() {
        return getChatId();
    }

    @Override
    @NotNull
    public ChatUrlRecord value1(@NotNull Long value) {
        setUrlId(value);
        return this;
    }

    @Override
    @NotNull
    public ChatUrlRecord value2(@NotNull Long value) {
        setChatId(value);
        return this;
    }

    @Override
    @NotNull
    public ChatUrlRecord values(@NotNull Long value1, @NotNull Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatUrlRecord
     */
    public ChatUrlRecord() {
        super(ChatUrl.CHAT_URL);
    }

    /**
     * Create a detached, initialised ChatUrlRecord
     */
    @ConstructorProperties({"urlId", "chatId"})
    public ChatUrlRecord(@NotNull Long urlId, @NotNull Long chatId) {
        super(ChatUrl.CHAT_URL);

        setUrlId(urlId);
        setChatId(chatId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ChatUrlRecord
     */
    public ChatUrlRecord(edu.java.domain.jooq.tables.pojos.ChatUrl value) {
        super(ChatUrl.CHAT_URL);

        if (value != null) {
            setUrlId(value.getUrlId());
            setChatId(value.getChatId());
            resetChangedOnNotNull();
        }
    }
}
